version: '2'
services:
    apigateway-postgresql:
        image: postgres:10.1-alpine
        # volumes:
        #     - ~/volumes/jhipster/ApiGateway/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=ApiGateway
            - POSTGRES_PASSWORD=
        ports:
            - 5431:5432
