apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: uaa-db
  name: uaa-db
  selfLink: /api/v1/namespaces/default/services/uaa-db
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    run: uaa-db
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
