apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: null
  generation: 1
  labels:
    run: uaa
  name: uaa
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/uaa
spec:
  replicas: 1
  selector:
    matchLabels:
      run: uaa
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: uaa
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev,swagger
        - name: EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE
          value: http://admin:admin@jhipster-registry:8761/eureka
        - name: SPRING_CLOUD_CONFIG_URI
          value: http://admin:admin@jhipster-registry:8761/config
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://uaa-db:5432/uaa
        - name: JHIPSTER_SLEEP
          value: "30"
        image: uaa
        imagePullPolicy: IfNotPresent
        name: uaa
        ports:
        - containerPort: 8080
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
